---
Layout/HashAlignment:
  Enabled: false

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Lint/Debugger:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Metrics/AbcSize:
  Max: 80

Metrics/BlockLength:
  Max: 100

Metrics/ClassLength:
  Max: 400

Metrics/CyclomaticComplexity:
  Max: 30

Metrics/ModuleLength:
  Max: 200

Metrics/PerceivedComplexity:
  Max: 40

Metrics/MethodLength:
  Max: 60

