---
Layout/HashAlignment:
  Enabled: false

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Layout::SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Lint/Debugger:
  Enabled: false

Style/NumericPredicate:
  Enabled: false
