---
Layout/HashAlignment:
  Enabled: false

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Lint/Debugger:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Metrics/AbcSize:
  Max: 34

Metrics/BlockLength:
  Max: 50

Metrics/ClassLength:
  Max: 200

Metrics/PerceivedComplexity:
  Max: 16

Metrics/MethodLength:
  Max: 40

Metrics/CyclomaticComplexity:
  Max: 14
