source 'http://rubygems.org'

#gem 'progress_bar'
gem 'activesupport'
gem 'byebug'
gem 'http'
gem 'listen'
gem 'mysql2'
gem 'nokogiri'
gem 'selenium-webdriver'
gem 'sequel'
gem 'sqlite3'
gem 'thor'
gem 'tty-box'
gem 'tty-cursor'
gem 'tty-pager'
gem 'tty-progressbar'
gem 'tty-prompt'
gem 'tty-spinner'
gem 'tty-table'
gem 'webdrivers'
gem 'code-scanning-rubocop'
gem 'rb-readline'

group 'music' do
  gem 'midi'
  gem 'mp4info', :git => 'https://github.com/arbarlow/ruby-mp4info.git'
  gem 'ruby-mp3info'
  gem 'taglib-ruby'
end

